const projetos = [
    {name: "app-crudjs", href:'https://github.com/ThiagoN13/app-crudjs'},
    {name: "aps-sd", href:'https://github.com/ThiagoN13/aps-sd'},
    {name:"ArquivosC", href:'https://github.com/ThiagoN13/AquivosC'},
    {name:"bookTip", href:'https://github.com/ThiagoN13/bookTip'},
    {name:"Cfiles", href:'https://github.com/ThiagoN13/Cfiles'},
    {name:"cidades-estados-brasil-json", href:'https://github.com/ThiagoN13/cidades-estados-brasil-json'},
    {name:"covid-statistics",href:'https://github.com/ThiagoN13/covid-statistics'},
    {name:"crud-php-laravel", href:'https://github.com/ThiagoN13/crud-php-laravel'},
    {name:"crudJS", href:'https://github.com/ThiagoN13/app-crudjs'},
    {name:"CrudPHP",href:'https://github.com/ThiagoN13/CrudPHP'},
    {name:"e-commerce",href:'https://github.com/ThiagoN13/e-commerce'},
    {name:"framework-frontend-semantic-ui", href:'https://github.com/ThiagoN13/framework-frontend-semantic-ui'},
    {name:"Game-Of-Python",href:'https://github.com/ThiagoN13/Game-of-Python'},
    {name:"learning-angularjs",href:'https://github.com/ThiagoN13/learning-angularjs'},
    {name:"magic-cube", href:'https://github.com/ThiagoN13/magic-cube'},
    {name:"portfolio", href:'https://github.com/ThiagoN13/portfolio'},
    {name:"portfolio-nextJS",href:'https://github.com/ThiagoN13/portfolio-nextjs'},
    {name:"Projeto-Integrador-PHP",href:'https://github.com/ThiagoN13/Projeto-Integrador-PHP'},
    {name:"projeto-reino-floral",href:'https://github.com/ThiagoN13/projeto-reino-floral'},
    {name:"projetoIntegradorWEB",href:'https://github.com/ThiagoN13/projetoIntegradorWEB'},
    {name:"react_cart",href:'https://github.com/ThiagoN13/react_cart'},
    {name:"react_insta",href:'https://github.com/ThiagoN13/react_insta'},
    {name:"react_relogio",href:'https://github.com/ThiagoN13/react_relogio'},
    {name:"Rede-Social-PHP", href:'https://github.com/ThiagoN13/Rede-Social-PHP'},
    {name:"sgce",href:'https://github.com/ThiagoN13/sgce'},
    {name:"snake-game",href:'https://github.com/ThiagoN13/snake-game'},
    {name:"tBook", href:'https://github.com/ThiagoN13/tBook'},
    {name:'treeview',href:'https://github.com/ThiagoN13/treeview'},
    {name:'video-stream-sample',href:'https://github.com/ThiagoN13/video-stream-sample'},



]
export default projetos 