const Projetos = [
    {name: "app-crudjs", href:'/'},
    {name: "aps-sd", href:'/'},
    {name:"ArquivosC", href:''},
    {name:"bookTip", href:''},
    {name:"Cfiles", href:''},
    {name:"cidades-estados-brasil-json", href:''},
    {name:"covid-statistics",href:''},
    {name:"crud-php-laravel", href:''},
    {name:"crudJS", href:''},
    {name:"CrudPHP",href:''},
    {name:"e-commerce",href:''},
    {name:"framework-frontend-semantic-ui", href:''},
    {name:"Game-Of-Python",href:''},
    {name:"learning-angularjs",href:''},
    {name:"magic-cube", href:''},
    {name:"portfolio", href:''},
    {name:"portfolio-nextJS",href:''},
    {name:"Projeto-Integrador-PHP",href:''},
    {name:"projeto-reino-floral",href:''},
    {name:"projetoIntegradorWEB",href:''},
    {name:"react_cart",href:''},
    {name:"react_insta",href:''},
    {name:"react_relogio",href:''},
    {name:"Rede-Social-PHP", href:''},
    {name:"sgce",href:''},
    {name:"snake-game",href:''},
    {name:"tBook", href:''},
    {name:'treeview',href:''},
    {name:'video-stream-sample',href:''},



]
export default Projetos 